"""Regenerate captions.md from manuscript.md.

captions.md had drifted: it still said "AI alloy" and "Omori alloy" after the Tier 0 rename
to "LLM-alloy"/"benchmark alloy", and it was two panels behind on Fig. 3. It is a derived
file, so derive it.

    python figures/extract_captions.py
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
HEADER = """# Figure captions

**Derived file — do not hand-edit.** Regenerate with `python figures/extract_captions.py`,
which reads the captions out of `manuscript.md`. That file is the source of truth; this one
exists so the figure set can be checked without opening the manuscript.

Figures 2, 4 and 6 come from `Cai_Fe-SMA_MaterialsDesign_Submission/Figures_and_Tables/`,
the set actually reviewed by Materials & Design. Figure 3 was extended for the JMRT R1
revision (`figures/build_fig3_with_benchmark.py`). Figures 1 (four-panel), 5, 7 (inverse
pole figures) and 8 (AGG diffraction) are S. Cai's, received 2026-08-12/13 and archived in
`revision/JMRT-R1/from-SCai-2026-08-13/`. Figure 9 is generated by
`revision/JMRT-R1/calphad/make_paper_figure.py`, and Figure 10 by
`figures/build_agg_figure.py` (sources and specimen identification in
`revision/JMRT-R1/processing/AGG-MICROGRAPH-PROVENANCE.md`).
"""

text = (ROOT / "manuscript.md").read_text(encoding="utf-8")
caps = re.findall(r"^!\[(.+?)\]\((figures/[^)]+)\)\s*$", text, re.M | re.S)

out = [HEADER]
for body, path in caps:
    out.append(f"{body.strip()}\n\n*File:* `{path}`")
(ROOT / "figures" / "captions.md").write_text("\n\n".join(out) + "\n", encoding="utf-8")
print(f"wrote figures/captions.md — {len(caps)} captions")
